apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.8
  clusterID: 783c241c-1c60-4e2f-912d-fe9b9c8a32f8
  desiredUpdate:
    version: 4.8.12
    image: quay.io/openshift-release-dev/ocp-release:4.8.12-x86_64
